-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(NVL(S.SALES * B.PRICE, 0)) AS TOTAL_SALES
  FROM BOOK B,
       (SELECT BOOK_ID, SUM(SALES) AS SALES
          FROM BOOK_SALES
         WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
         GROUP BY BOOK_ID) S,
       AUTHOR A
 WHERE B.BOOK_ID = S.BOOK_ID
   AND B.AUTHOR_ID = A.AUTHOR_ID
 GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
 ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;
