--코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
  FROM FOOD_ORDER O, FOOD_PRODUCT P
 WHERE O.PRODUCT_ID = P.PRODUCT_ID
   AND TO_CHAR(O.PRODUCE_DATE, 'YYYYMM') = '202205'
 GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID;
